---
title: "ps_5_BeauMeche"
author: "Beau Meche"
date: "March 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#choose your toolbox wisely as to always be prepared
library(tidyverse)
library(readr)
library(janitor)
library(gt)
library(fs)
library(lubridate)
```

```{r echo=FALSE, message=FALSE, cache=TRUE}
#download the file remotely so I don't have to update the link
download.file(url = "https://www.fec.gov/files/bulk-downloads/2006/weball06.zip",
              # name the file for retrieval
              destfile = "weball06.zip", 
              mode = "wb")

# assign the read file to something to avoid typing too much
x <- read_delim("weball06.zip", delim = "|", col_names = FALSE) %>%
  
  #transmute the cols that we need and assign the relevant names
  #col references are tricky and are found in the data explanation 
  # on the download website
  transmute(cand_id = X1,
            cand_name = X2, 
            party = X5, 
            cash = X11,
            cand_state = X19
            )

#delete file for memory and ease of running this file later
file_delete("weball06.zip")

```

#Question 1
```{r echo=FALSE, message=FALSE, cache=FALSE}
ML1 <- x %>%
  # we are looking at states
  group_by(cand_state) %>%
  count() %>%
  # want the largest values first
  arrange(desc(n)) %>%
  ungroup() %>%
  # select the row value that we want now that the tibble is only states and integers
  slice(3)

ML2 <- x %>%
  # create a col of name lengths
  mutate(name_length = str_length(cand_name)) %>%
  # look at the longest ones first
  arrange(desc(name_length)) %>%
  # create a col of names that are normally capitalized for name uses
  mutate(nice_name = str_to_title(cand_name)) %>%
  # break up the legal document format of the name into first and last 
  separate(nice_name, into = c("last_n", "first_n"), sep = ",") %>%
  # "stick" the names back together in a homogeneous form
  mutate(full_name = paste(first_n, last_n)) %>%
  ungroup() %>%
  # select the row with the value we want, the variable can be accessed in the inline code later
  slice(5)

ML3 <- x %>%
  # fix the capitalization to be normal in a new column
  mutate(nice_name = str_to_title(cand_name)) %>%
  # break the 1st and last names into cols
  separate(nice_name, into = c("last_n", "first_n"), sep = ",") %>%
  # find length of the last name
  mutate(name_length = str_length(last_n)) %>%
  # look at the longest surnames
  arrange(desc(name_length)) %>%
  # paste the names back together in readable form for display later
  mutate(full_name = paste(first_n, last_n)) %>%
  ungroup() %>%
  # select the row with the value we want, the variable can be accessed in the inline code later
  slice(1)
```
The state with the 3rd most rows is `r ML1$cand_state`.

The candidate with the 5th longest full name is `r ML2$full_name`.

The candidate with the longest last name is `r ML3$full_name`.

#Question 2
```{r echo=FALSE, message=FALSE, warning=FALSE}
q2 <- x %>%
  # "collapse" all of the entries that are labeled with different syntactical forms of an abbreviation for the respective parties
  mutate(party = fct_collapse(party,
                "Republican" = c("REP", "Rep", "rep"),
                "Democrat" = c("DEM", "Dem", "DFL"))) %>%
  # we want this part of the data to be organized by party
  group_by(party) %>%
  # find the aggregate end-cash holdings
  summarize(party_cash = sum(cash)) %>%
  # look at teh biggest holders
  arrange(desc(party_cash)) %>%
  # label the rows nicely
  mutate(party = case_when(party == "IND" ~ "Independent", 
                           party == "Republican" ~ "Republican",
                           party == "Democrat" ~ "Democrat",
                           party == "OTH" ~ "Other", 
                           party == "LIB" ~ "Libertarian")) %>%
  # grab the first 5 rows
  head(5) %>%
  # make a table
  gt() %>%
  # add the "$" and appropriate decimal for the currency
  fmt_currency(vars(party_cash), currency = "USD") %>%
  # label the table appropriately
  cols_label(party = "Party", 
             party_cash = "Total Donated") %>%
  tab_header("Total Donations to the 5 Largest Parties (USD)") %>%
  tab_source_note("Source data courtesy of the FEC")
q2
```


#Question 3
```{r echo=FALSE, message=FALSE, cache=TRUE}
# download the dataset file
download.file(url = "https://www.fec.gov/files/bulk-downloads/2006/cm06.zip",
              # name the file for retrieval 
              destfile = "cm06.zip", 
              mode = "wb")
# read the file and assign it for later use without a full reload
w <- read_delim("cm06.zip", delim = "|", col_names = FALSE, escape_double = TRUE) %>%
  # select and name the relevant columns (again, names found in the data set explanation webpage)
  transmute(cand_id = X15,
            cmte_id = X1,
            cmte_party = X11)
#delete file for memory and ease of running this file later
file_delete("cm06.zip")
```

```{r echo=FALSE, cache=FALSE}
step1 <- w %>% 
    # we need committee party affiliation to exist
    filter(!is.na(cmte_party)) %>%
    # again we need to condense all of the various names for the same things, and in this case we want all extraneous groups to be grouped together (hence the else: TRUE clause)
    mutate(cmte_party = case_when(
    cmte_party %in% c("REP", "rep", "Rep") ~ "Republican", 
    cmte_party %in% c("DEM", "Dem", "dem") ~ "Democrat", 
    TRUE ~ "Other")) %>%
  # we want the data to be displayed by party
  group_by(cmte_party) %>%
  # find the distinct comittees and candidates
  summarize(committees = n_distinct(cmte_id), candidates = n_distinct(cand_id)) %>%
  # I used this to reorder the rows without a drastic relabeling effort, it was certainly the easy way out but in the nature of the real world I choose to have results efficiently when possible
  arrange(desc(committees)) %>%
  ungroup() %>%
  # make a table with your nice data
  gt() %>%
  # label said table appropriately
  cols_label(cmte_party = "Party", 
             committees = "Comittees", 
             candidates = "Candidates") %>%
  tab_header("Committees and Candidates  by Party") %>%
  tab_source_note("Source data courtesy of the FEC")
step1
```


#Question 4
```{r echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
#download portion of Question 4
download.file(url = "https://www.fec.gov/files/bulk-downloads/2006/indiv06.zip",
              destfile = "indiv06.zip", 
              mode = "wb")
# read the file and assign it for later use without a full reload
blend <- read_delim("indiv06.zip", delim = "|", col_names = FALSE, escape_double = FALSE, guess_max = 10000)

#delete file for memory and ease of running this file later
file_delete("indiv06.zip")
```

```{r echo=FALSE, message=FALSE, cache=FALSE}
#create the dataframe needed for the 4th question
# select and name the desired columns fromm our 'raw' data
blend1 <- blend %>%
  transmute(cmte_id = X1,
            date = X14,
            amount = X15, 
            employer = X12, 
            occupation = X13)

  # join the 3rd dataset to the second
  merged <- left_join(w, blend1, by = "cmte_id")
  # join the resulting dataset to the first, now we have the data needed for the 4th question
  join2 <- left_join(merged, x, by = "cand_id")
  
  # store the data for the next question via Rpubs
  write_rds(join2, "Join2.rds")
```

```{r echo=FALSE, cache=FALSE}
  join2 %>%
    # create employers column with a normally capitalized formatting
    mutate(employer = str_to_title(employer)) %>%
    # look at only harvard professors
    filter(employer == "Harvard University",
           str_detect(occupation, "PROFESSOR"),
           # party must be defined
           !is.na(party)) %>%
    # only want donors
    filter(amount > 0) %>%
    # cut out data that isnt needed
    select(date, party) %>%
    # condense the redundant party names
    mutate(party = case_when(party %in% c("REP", "rep", "Rep") ~ "Republican", 
                             party %in% c("DEM", "Dem", "dem") ~ "Democrat")) %>%
    # format the dates into a usable form
    mutate(date = parse_date(date, format = "%m %d %Y")) %>%
    # turn date entries into yearly quarters
    mutate(date = cut(date, breaks = "quarters")) %>% 
    group_by(date, party) %>%
    # count number of donations regardless of value
    summarize(donations = n()) %>%
    # flip the tibble value dimensions for the variables in question
    spread(party, donations, fill = 0) %>%
    ungroup() %>%
    # create table and label acccordingly
    gt() %>%
    cols_label(date = "Qtr. Date") %>%
    tab_header("Harvard Professors' Donation Count by Party") %>%
    tab_source_note("Source data courtesy of the FEC")
```

#Question 5

http://rpubs.com/BeauM/H_employee_donations_50-06



#Colleagues
Debora G., Tate G., Neil K., Henry Z., Mike S., and Igor M. 