---
title: "ps_5_graphic"
author: "Beau Meche"
date: "March 5, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(janitor)
library(gt)
library(fs)
library(lubridate)
```

```{r cache=FALSE, echo=FALSE}
# read in the same dataset used in problem 4
data5 <- read_rds("Join2.rds")
```

```{r echo=FALSE}
#assign to a name
q5<- data5 %>%
  # only harvard employees
  filter(employer == "HARVARD UNIVERSITY") %>%
  # condense redundant names for dems, republicans, and other while adding a 'non-partisan option for committees, I chose to do this because some people donate to causes that are allied with parties (cmte_party) but are not necessarily inherently a partisan organization
  mutate(party = case_when(party %in% c("REP", "rep", "Rep") ~ "Republican", 
                           party %in% c("DEM", "Dem", "dem") ~ "Democrat", 
                           !is.na(party) ~ "Non-Partisan",
                           TRUE ~ "Other"
                           )) %>%
  # format the date
  mutate(date = parse_date(date, format = "%m %d %Y")) %>%
  # establish a quarterly division
  mutate(date = cut(date, breaks = "quarters")) %>%
  select(date, occupation, party, amount) %>%
  # plot the data in geom_jjitter to see the concentration of points (donations) of varying sizes to different parties (or non-partisan groups) over the 2 years
  ggplot(aes(x = date, y = amount, color = party)) + geom_jitter(aes(size = amount, alpha = .7), show.legend = FALSE) +               scale_y_log10() + 
  # republican red and democrat blue... green is non-partisan and orange is other
  scale_color_manual(breaks = c("8", "6", "4", "5"),
                        values=c("blue", "orange", "green", "red")) +
  # label as necessary
  labs(title = "Harvard Employee Political Constituency '05-'06", 
       subtitle = "partisan and non-partisan recipients", 
       caption = "Source data courtesy of the FEC")+
  xlab("Date of Donation") +
  ylab("Amount Donated (USD)")
q5

```



